# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhoneContacts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhoneContacts
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon', :branch => 'swift5'
pod "LetterAvatarKit", "1.2.3" # Swift 5.0+

end
